### PR TITLE
Export and import functionality and global profile

### PR DESCRIPTION
**Pull request by da-the-dev**
I've decided to poke around this beautiful extension and tried shrinking the *"idea list"* (#1) by implementing the import and export functionality for profiles. Basically I've reused `createProfile()` and `deleteProfile()` functions and just added file save/open prompts and actual profile file export/import. 

Profiles are exported/imported into/from `.json` files. When exporting, the name of the selected profile is used as a name for the file and when importing the same file name is used for the profile name *(profile name is "test" -> exports into "test.json". File name is "123.json" -> gets imported into a new profile "123")*. 

I've been thinking what should be the default path to export profiles and I decided to use the 'Documents' folder. Its path varies from system to system, so I've implemented `pathToDocuments()`, but I don't have a machine with Windows ATM, though I've tested the extension on Mac and Linux (Ubuntu 20.04) and it works as expected. I'm hoping to get access to one soon, but for now feel free finish the `pathToDocuments()` function. I've added comments so it's easier to understand.

P.S. There are some cosmetic changes that came from me fixing the `.eslintrc`'s `curly` rule, hope you don't mind.

### CODE REVIEW

**Comment by evald24** [comment]
@da-the-dev you're doing great, thank you so much for PR.

I fixed minor bugs, did refactoring and added support for multilingual extensions #16.

**Comment by da-the-dev** [comment]
@evald24 Thank you so much!

**Comment by da-the-dev** [comment]
@evald24 I've create a VM with Windows 10 installed and tried the extension, it work flawlessly! The `homedir()` function is a very good idea! I believe it is ready for 1.0.10.

**Comment by da-the-dev** [comment]
I've also added Global Profile functionality. A few folks from #1 requested a sort of global profile that would apply alongside every other profile. I've added a function to update it *`(updateGlobalProfile)`*, a command to import it *`(importGlobalProfile)`*, extended `exportProfile()` to be able to export it and also modified `createProfile()`, `editProfile()` and `deleteProfile()` to not show the Global Profile in the selection list. Cosmetic changes here and there.

Right now I'm thinking of somehow integrating syncing, but I suppose I'll need to revamp profiles as a whole so that they could be individually applied and disabled.

**Comment by evald24** [comment]
@da-the-dev great job, I'll watch and test it tomorrow)

**Comment by da-the-dev** [comment]
I've simplified how global profile works, it used to be some over-engineered over-the-top profile that had separate functions for it, now it's just a profile that you can't delete and is applied along side every other profile.

**Comment by evald24** [comment]
@da-the-dev Hi! Can you explain the meaning of "Global Profile" if it is no different from a regular profile?

**Comment by evald24** [comment]
Added support for "WSL" #19

**Comment by evald24** [comment]
@da-the-dev I'm sorry, I was sick and could not fully understand the idea =)

Congratulations on this first minor update 🥳

**Pull request merged**
